name: aoc_2024
description: Advent of Code 2024 solutions
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  collection: ^1.19.1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
